version: 2.1

jobs:
  notify_discord:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Send Discord Notification
          command: |
            curl -H "Content-Type: application/json" -X POST -d '{"content": "Repo `batv8`: Finish flow `run-and-test`"}' https://discord.com/api/webhooks/1411725325150457866/CGB4PzlL5OLBDT2uv3UDU1qArAr1MAjf19Vqodyx00KfrWdppW6pvo7yN9yfhHdrcflg

workflows:
  version: 2
  notify:
    jobs:
      - notify_discord